#!/usr/bin/env python3
"""Regenerate the dark theme block in index.html from the current light styles.

The review UI hard-codes light colors in many rules. This maps each literal to its GitHub-dark
counterpart (Holonic teal for brand accents) and writes one `:root[data-theme=dark]` override per
rule into <style id="holonic-dark-theme">. Run it after adding or changing light colors:

    python3 github-lambda-workflow/review-prototype/build_dark_theme.py
"""
from __future__ import annotations

from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
INDEX = HERE / "index.html"
EXTRA_CSS = sorted((HERE / "assets").glob("*.css"))
START, END = '<style id="holonic-dark-theme">', "</style>"

DARK = {
    "white": "#161b22", "#fff": "#161b22", "#ffffff": "#161b22", "#f6f8fa": "#0d1117",
    "#f8fbff": "#0d1117", "#fbf9ff": "#161b22", "#eaeef2": "#21262d", "#dbe5ef": "#21262d",
    "#d0d7de": "#30363d", "#afb8c1": "#484f58", "#8c959f": "#6e7681", "#6e7781": "#6e7681",
    "#656d76": "#8b949e", "#57606a": "#8b949e", "#1f2328": "#e6edf3", "#25292e": "#010409",
    "#ddf4ff": "#121d2f", "#b6d5f7": "#1f4a7a", "#54aeff": "#58a6ff", "#0969da": "#4493f8",
    "#0550ae": "#79c0ff", "#ffebe9": "#2d1517", "#fff1f0": "#2d1517", "#cf222e": "#f85149",
    "#82071e": "#ffa198", "#a40e26": "#ff7b72", "#46272b": "#ffa198", "#e6ffec": "#12261b",
    "#dafbe1": "#12261b", "#1a7f37": "#3fb950", "#116329": "#56d364", "#203b2a": "#7ee2a8",
    "#fff8e6": "#2b2111", "#fff8c5": "#2b2111", "#f0d9a5": "#5a4517", "#9a6700": "#d29922",
    "#72551c": "#e3b341", "#bf8700": "#d29922", "#3a321d": "#e3b341", "#633c01": "#e3b341",
    "#f5f0ff": "#1e1730", "#ede4ff": "#271d3f", "#b49bea": "#6e4fb0", "#8250df": "#ab7df8",
    "#6639a6": "#d2a8ff", "#4c2889": "#d2a8ff", "#65459a": "#d2a8ff", "#fff0e5": "#2b1a10",
    "#ff9157": "#ffa657", "#fd8c73": "#3fa58c", "#b64a16": "#ffa657", "#e6f3ef": "#12322a",
}
LITERAL = re.compile(r"#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b|\bwhite\b", re.I)

BASE = """:root[data-theme=dark]{color-scheme:dark;--bg:#0d1117;--panel:#161b22;--ink:#e6edf3;--muted:#8b949e;--line:#30363d;--blue:#4493f8;--green:#3fb950;--red:#f85149;--amber:#d29922;--purple:#ab7df8;--brand:#3fa58c;--brand-deep:#256352;--red-bg:#2d1517;--amber-bg:#2b2111}
:root[data-theme=dark] body{background:var(--bg);color:var(--ink)}
:root[data-theme=dark] .top{background:#010409;border-bottom:1px solid var(--line)}
:root[data-theme=dark] .holonic-brand{background:#e6edf3;border-radius:6px;padding:2px}
:root[data-theme=dark] a{color:#4493f8}
.theme-toggle{margin-left:12px;background:transparent;color:#e6edf3;border:1px solid #484f58;border-radius:6px;padding:4px 10px;font:inherit;font-size:12px;cursor:pointer}
.theme-toggle:hover{border-color:#3fa58c}.theme-toggle:focus-visible{outline:2px solid #3fa58c;outline-offset:2px}
.top a{white-space:nowrap}"""
# Applied last so they win over generated rules.
FINAL = """:root[data-theme=dark] .top a{color:#e6edf3}"""


def _rules(css: str):
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    css = re.sub(r"@(?:media|supports|keyframes)[^{]*\{(?:[^{}]*\{[^{}]*\})*[^{}]*\}", "", css)
    for match in re.finditer(r"([^{}]+)\{([^{}]*)\}", css):
        yield match.group(1).strip(), match.group(2)


def overrides(css: str) -> list[str]:
    out = []
    for selector, declarations in _rules(css):
        if selector.startswith("@") or ":root[data-theme" in selector or not LITERAL.search(declarations):
            continue
        props = []
        for declaration in declarations.split(";"):
            if ":" not in declaration:
                continue
            name, value = declaration.split(":", 1)
            if not LITERAL.search(value) or (name.strip() == "color" and value.strip().lower() == "white"):
                continue
            mapped = LITERAL.sub(lambda m: DARK.get(m.group(0).lower(), m.group(0)), value)
            if mapped != value:
                props.append(f"{name.strip()}:{mapped.strip()}")
        if props:
            scoped = ",".join(":root[data-theme=dark] " + s.strip() for s in selector.split(",") if s.strip())
            out.append(scoped + "{" + ";".join(props) + "}")
    return out


def main() -> None:
    html = INDEX.read_text()
    start = html.index(START)
    end = html.index(END, start)
    light = re.sub(re.escape(START) + r".*?" + re.escape(END), "", html, flags=re.S)
    css = "\n".join(re.findall(r"<style[^>]*>(.*?)</style>", light, re.S))
    css += "\n" + "\n".join(path.read_text() for path in EXTRA_CSS)
    unmapped = sorted({m.group(0).lower() for m in LITERAL.finditer(css)} - set(DARK) - {"#000", "#000000"})
    block = (START + "\n/* Generated by build_dark_theme.py: GitHub dark palette, Holonic teal accent. */\n"
             + BASE + "\n" + "\n".join(overrides(css)) + "\n" + FINAL + "\n")
    INDEX.write_text(html[:start] + block + html[end:])
    print(f"{len(overrides(css))} override rules; unmapped literals: {', '.join(unmapped) or 'none'}")


if __name__ == "__main__":
    main()
